@startuml

class bambuk_rpc {

  {abstract}agent_state: state(server_conf)
  {abstract}boolean: apply(connect_db)
  {abstract}boolean: update(connect_db_update)

}

class agent_state {
   must return the agent map defining it: check with ovs_agent
}

class server_conf {
   server_ip
}

class connect_db {
   vifs
   security_groups
   fdp_entries
}

class connect_db_update {
    action: create|delete|replace
    entity
    id
    value
}

@enduml