SCRIPTS_PATH=`pwd`
IMAGES_PATH=/var/lib/libvirt/images
TEMPLATES_PATH=$SCRIPTS_PATH/templates
TEMPLATE_NAME=vm-template
TEMPLATE_FILE=$TEMPLATES_PATH/$TEMPLATE_NAME.xml
TEMPLATE_DISK=$IMAGES_PATH/$TEMPLATE_NAME.qcow2
cd $SCRIPTS_PATH

